In [8]:
import numpy
def change(a, indx, indy):
    a[indx, indy] += 1
a = numpy.zeros((2, 10))
print(a)
change(a, 1, 1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
